comThree = arduino('COM6','Uno')
SongNum=randi([1,8])
CEight = 4186;
BSeven = 3951.1;
ASevenSrp = 3729.3;
ASeven = 3520;
GSevenSrp = 3322.4;
GSeven = 3136;
FSevenSrp = 2960;
FSeven = 2793.8;
ESeven = 2637;
DSevenSrp = 2489;
DSeven = 2349.3;
CSevenSrp = 2217.5;
CSeven = 2093;
BSix = 1975.5;
ASixSrp = 1864.7;
ASix = 1760;
GSixSrp = 1661.2;
GSix = 1568;
FSixSrp = 1480;
FSix = 1396.9;
ESix = 1318.5;
DSixSrp = 1244.5;
DSix = 1174.7;
CSixSrp = 1108.7;
CSix = 1046.5;
BFive = 987.77;
AFiveSrp = 932.33;
AFive = 880;
GFiveSrp = 830.61;
GFive = 783.99;
FFiveSrp = 739.99;
FFive = 698.46;
EFive = 659.26;
DFiveSrp = 622.25;
DFive = 587.33;
CFiveSrp = 554.37;
CFive = 523.25;
BFourSrp=523.251;
BFour = 493.88;
AFourSrp = 466.16;
AFour = 440;
GFourSrp = 415.3;
GFour = 392;
FFourSrp = 369.99;
FFour = 349.23;
EFour = 329.63;
DFourSrp = 311.13;
DFour = 293.67;
CFourSrp = 277.18;
CFour = 261.6;
BThree = 246.94;
AThreeSrp = 233.08;
AThree = 220;
GThreeSrp = 207.65;
GThree = 196;
FThreeSrp = 185;
FThree = 174.61;
EThree = 164.81;
DThreeSrp = 155.56;
DThree = 146.83;
CThreeSrp = 138.59;
CThree = 130.81;
BTwo = 123.47;
ATwoSrp = 116.54;
ATwo  = 110;
GTwoSrp = 103.83;
GTwo = 97.999;
FTwoSrp = 92.499;
FTwo = 87.307;
ETwo = 82.407;
DTwoSrp = 77.782;
DTwo = 73.416;
CTwoSrp = 69.296;
CTwo = 65.406;
BOne = 61.735;
AOneSrp = 58.27;
AOne = 55;
GOneSrp = 51.913;
GOne = 48.999;
FOneSrp = 46.249;
FOne = 43.654;
EOne = 41.203;
DOneSrp = 38.891;
DOne = 36.708;
ConeSrp = 34.648;
COne = 32.703;
BZero = 30.868;
AZeroSrp = 29.135;
AZero = 27.5;
Rest = 0; 
Whole = 1; 
Quarter = Whole/4;
Half = Quarter*2;
Eighth=Quarter/2;
Sixteenth = (Eighth/2);
DottedEighth = (Sixteenth*3);
DottedQuarter = (Eighth*3);
DottedHalf = (Quarter*3);
ThirtySecond = (Eighth/2);
AlarmSongMega = [DFour,Sixteenth; DFour, Sixteenth; DFive, DottedEighth;...
AFour, DottedEighth; Rest, Sixteenth; GFourSrp, Sixteenth; Rest, Sixteenth;...
GFour, Sixteenth; Rest, Sixteenth; FFour, Sixteenth; FFour, Sixteenth; DFour, Sixteenth;...
FFour, Sixteenth; GFour, Sixteenth; CFour, Sixteenth; CFour, Sixteenth; ...
DFive, DottedEighth; AFour, DottedEighth; Rest, Sixteenth; GFourSrp, Sixteenth;...
Rest, Sixteenth; GFour, Sixteenth; Rest, Sixteenth; FFour, Sixteenth;...
FFour, Sixteenth; DFour, Sixteenth; FFour, Sixteenth; GFour, Sixteenth;...
BThree,Sixteenth; BThree, Sixteenth; DFive, DottedEighth; AFour, DottedEighth;...
Rest, Sixteenth; GFourSrp, Sixteenth; Rest, Sixteenth; GFour, Sixteenth; Rest, Sixteenth;...
FFour, Sixteenth; FFour, Sixteenth; DFour, Sixteenth; FFour, Sixteenth; GFour, Sixteenth;...
AThreeSrp, Sixteenth; AThreeSrp, Sixteenth; DFive, DottedEighth; AFour, DottedEighth;...
Rest, Sixteenth; GFourSrp, Sixteenth; Rest, Sixteenth; GFour, Sixteenth; Rest, Sixteenth;...
FFour, Sixteenth; FFour, Sixteenth; DFour, Sixteenth; FFour, Sixteenth; GFour, Sixteenth;...
];
AlarmSongCommrad = [CFive,Quarter; GFour,DottedEighth;AFour,Sixteenth; BFour, Quarter;...
EFour, Eighth; EFour, Eighth; AFour,Quarter; GFour, DottedEighth; FFour, Eighth;...
GFour, Quarter; CFour, DottedEighth; CFour, Sixteenth; DFour, Quarter; DFour, DottedEighth;...
EFour, Sixteenth; FFour, Quarter; FFour, DottedEighth; GFour, Sixteenth; AFour, Quarter;...
BFour, DottedEighth; CFive, Sixteenth; DFive, DottedQuarter;GFour, Eighth; EFive, Quarter;...
DFive, DottedEighth; CFive, Sixteenth; DFive, Quarter; BFour, DottedEighth; GFour, Sixteenth;...
CFive, Quarter; BFour, DottedEighth; AFour, Sixteenth; BFour, Quarter; EFour, DottedEighth;...
EFour, Sixteenth; AFour, Quarter; GFour, DottedEighth; FFour, Sixteenth; GFour, Quarter;...
CFour, DottedEighth; CFour, Sixteenth; CFive, Quarter; BFour, DottedEighth; AFour, Sixteenth;...
GFour, Half; EFive, Half; DFive, Eighth; CFive, Eighth; BFour, Eighth; CFive, Eighth;...
DFive, DottedQuarter; GFour, Eighth; GFour, Half; CFive, Half; BFour, Eighth; AFour, Eighth;...
GFour, Eighth; AFour, Eighth; BFour, DottedQuarter; EFour, Eighth; EFour, Half; CFive, Quarter;...
AFour, DottedEighth; BFour, Sixteenth; CFive, Quarter; AFour, DottedEighth; BFour, Sixteenth;...
CFive, Quarter; AFour, DottedEighth; CFive, Sixteenth; FFive, Half; FFive, Half; EFive, Eighth;...
DFive, Eighth; CFive, Eighth; DFive, Eighth; EFive, DottedQuarter; CFive, Eighth; CFive, Half;...
DFive, Half; CFive, Eighth; BFour, Eighth; AFour, Eighth; BFour, Eighth; CFive, DottedQuarter;...
AFour, Eighth; AFour, Half; CFive, Quarter; BFour, DottedEighth; AFour, Sixteenth; GFour, Quarter;...
CFour, DottedEighth; CFour, Sixteenth; CFive, Quarter; BFour,DottedEighth; AFour, Sixteenth;...
GFour, DottedQuarter; GFour, Eighth;];
AlarmSongCallMe = [BFour,Eighth; BFour,Eighth;BFour,Eighth;BFour,Eighth;BFour,Eighth;AFour,Eighth;BFour,Eighth;...
Rest,Eighth; BFour,Eighth; BFour,Eighth;BFour,Eighth;BFour,Eighth;BFour,Eighth;AFour,Eighth;BFour,Eighth;...
Rest,Eighth; BFour,Eighth; BFour,Eighth;BFour,Eighth;BFour,Eighth;BFour,Eighth;AFour,Eighth;AFour,Eighth;...
Rest,Eighth;AFour,Eighth;AFour,Eighth;GFour,Eighth;DFive,Quarter;BFour,Eighth;Rest,Eighth;BFour,Eighth;...
BFour,Eighth;BFour,Eighth;BFour,Eighth;BFour,Eighth;AFour,Eighth;BFour,Eighth;BFour,Eighth;BFour,Eighth;...
BFour,Eighth;BFour,Eighth;BFour,Eighth;AFour,Eighth;BFour,Eighth;BFour,Eighth;BFour,Eighth;BFour,Eighth;...
BFour,Eighth;BFour,Eighth;AFour,Eighth;AFour,Eighth;Rest,Eighth;AFour,Eighth;AFour,Eighth;GFour,Eighth;...
GFour,Eighth;DFive,Quarter;BFour,Eighth;Rest,Quarter;DFive,Quarter;DFive,DottedEighth;BFour,Sixteenth;...
AFour,Eighth;GFour,Eighth;DFive,Quarter;DFive,Quarter;DFive,DottedEighth;BFour,Sixteenth;AFour,Eighth;...
GFour,Eighth;EFive,Quarter;EFive,Eighth;EFive,Eighth;EFive,Quarter;FFive,Eighth;GFive,Eighth;...
Rest,Quarter;GFive,Quarter;BFour,Sixteenth;DFive,Eighth;GFive,Eighth;DFive,DottedEighth;Rest,DottedQuarter;...
BFour,DottedEighth;DFive,Eighth;BFive,Sixteenth;BFive,Eighth;GFive,Eighth;Rest,DottedQuarter;...
GFive,Eighth;BFive,Eighth;CSix,Eighth;BFive,Eighth;GFive,Eighth;Rest,DottedQuarter;GFive,Eighth;...
BFive,Eighth;AFive,Eighth;AFive,Eighth;GFive,Eighth;ESix,Quarter;GFive,Quarter;BFour,Sixteenth;...
DFive,Eighth;GFive,Eighth;DSix,Eighth;Rest,Half;BFour,Eighth;DFive,Eighth;BFive,Eighth;GSix,Eighth;...
Rest,Eighth;GFive,Eighth;Rest,Eighth;CSix,Eighth;BFive,Eighth;AFive,Eighth;AFive,Eighth;GFive,Eighth;];
AlarmSongPuppet = [EFour,Quarter; Rest,Quarter; Rest,Half; DFive,Quarter; CFive,Quarter; CFive,Half;...
CFive,Whole; EFour,Eighth; EFour,Eighth; EFive,Eighth; EFour,Eighth; EFour,Eighth; DFiveSrp,Eighth;...
EFour,Eighth; EFour,Eighth; DFive,Quarter; CFive,Quarter; EFour,Eighth; EFour,Eighth; BFour,Eighth;...
EFour,Eighth; EFour,Eighth; BFourSrp,Eighth; EFour,Eighth; EFour,Eighth; AFour,Eighth; EFour, Eighth;...
GFour,Eighth; EFour,Eighth; GFour,Eighth; EFour,Eighth; FFour,Eighth; EFour,Eighth; EFour,Eighth;...
EFour,Eighth; EFive,Eighth; EFour,Eighth; EFour,Eighth; DFiveSrp,Eighth; EFour,Eighth; EFour,Eighth;...
DFive,Quarter; CFive,Quarter; CFive,Half; EFour, Eighth; EFour,Eighth; BFour,Eighth; EFour,Eighth;...
EFour,Eighth; AFourSrp,Eighth; EFour,Eighth; EFour,Eighth; AFour,Eighth; EFour, Eighth; GFour,Eighth;...
EFour,Eighth; GFour,Eighth; EFour,Eighth; FFour,Eighth; EFour,Eighth; EFour,Eighth; EFour,Eighth;...
EFive,Eighth; EFour,Eighth; EFour,Eighth; DFiveSrp,Eighth; EFour,Eighth; EFour,Eighth; DFive,Quarter;...
CFive,Quarter; CFive,Half; EFour, Eighth; EFour,Eighth; BFour,Eighth; EFour,Eighth; EFour,Eighth;...
AFourSrp,Eighth; EFour,Eighth; EFour,Eighth; AFour,Eighth; EFour, Eighth; GFour,Eighth; EFour,Eighth;...
GFour,Eighth; EFour,Eighth; FFour,Eighth; EFour,Eighth; EFour,Eighth; EFour,Eighth; EFive,Eighth;...
EFour,Eighth; EFour,Eighth; DFiveSrp,Eighth; EFour,Eighth; EFour,Eighth; DFive,Quarter; CFive,Quarter;...
CFive,Half; EFour, Eighth; EFour,Eighth; BFour,Eighth; EFour,Eighth; EFour,Eighth; AFourSrp,Eighth;...
EFour,Eighth; EFour,Eighth; AFour,Eighth; EFour, Eighth; GFour,Eighth; EFour,Eighth; GFour,Eighth;...
EFour,Eighth; FFour,Eighth; EFour,Eighth; EFour,Eighth; EFour,Eighth; EFive,Eighth; EFour,Eighth;...
EFour,Eighth; DFiveSrp,Eighth; EFour,Eighth; EFour,Eighth; DFive,Quarter; CFive,Quarter; CFive,Half;...
EFour, Eighth; EFour,Eighth; BFour,Eighth; EFour,Eighth; EFour,Eighth; AFourSrp,Eighth;...
EFour,Eighth; EFour,Eighth; AFour,Eighth; EFour,Eighth; GFour,Eighth; EFour,Eighth; GFour,Eighth;...
EFour,Eighth; FFour,Eighth; EFour,Eighth; EFour,Eighth; FFour,Eighth; BFour,Eighth;...
EFour,Eighth; FFour,Eighth; CFive,Eighth; EFour,Eighth; FFour,Eighth; CFive,Eighth; EFour,Eighth;...
FFour,Eighth; CFive,Eighth; EFour,Eighth; FFour,Eighth; BFour,Eighth; BFour,Eighth; EFour,Eighth;...
FFour,Eighth; BFour,Eighth; EFour,Eighth; FFour,Eighth; CFive,Eighth; EFour,Eighth; FFour,Eighth;...
GFour,Eighth; FFour,Eighth; GFour,Quarter; FFour,Quarter; GFour,Eighth; FFour,Eighth; EFour,Eighth;...
FFour,Eighth; BFour,Eighth; EFour,Eighth; FFour,Eighth; CFive,Eighth; EFour,Eighth; FFour,Eighth;...
CFive,Eighth; EFour,Eighth; FFour,Eighth; CFive,Eighth; EFour,Eighth; FFour,Eighth; BFour,Eighth;...
BFour,Eighth; EFour,Eighth; FFour,Eighth; BFour,Eighth; EFour,Eighth; FFour,Eighth; CFive,Eighth;...
EFour,Eighth; FFour,Eighth; GFour,Eighth; FFour,Eighth; GFour,Quarter; FFour,Quarter; GFour,Eighth;...
FFour,Eighth; EFour,Eighth; FFour,Eighth; BFour,Eighth; EFour,Eighth; FFour,Eighth; CFive,Eighth;...
EFour,Eighth; FFour,Eighth; CFive,Eighth; EFour,Eighth; FFour,Eighth; CFive,Eighth; EFour,Eighth;...
FFour,Eighth; BFour,Eighth; BFour,Eighth; EFour,Eighth; FFour,Eighth; BFour,Eighth; EFour,Eighth;...
FFour,Eighth; CFive,Eighth; EFour,Eighth; FFour,Eighth; CFive,Eighth; EFour,Eighth; FFour,Eighth;...
CFive,Eighth; EFour,Eighth; FFour,Eighth; BFour,Eighth; EFour,Eighth; FFour,Eighth; BFour,Eighth;...
EFour,Eighth; FFour,Eighth; CFive,Eighth; EFour,Eighth; FFour,Eighth; CFive,Eighth; EFour,Eighth;...
FFour,Eighth; CFive,Eighth; EFour,Eighth; FFour,Eighth; BFour,Eighth; BFour,Eighth; EFour,Eighth;...
FFour,Eighth; BFour,Eighth; EFour,Eighth; FFour,Eighth; CFive,Eighth; EFour,Eighth; FFour,Eighth;...
GFour,Eighth;FFour,Eighth; Rest,Eighth; GFour,Eighth; FFour,Eighth; Rest,Eighth; GFour,Eighth; FFour,Eighth;...
EFour,Eighth; FFour,Eighth; BFour,Eighth; EFour,Eighth; FFour,Eighth; CFive,Eighth; EFour,Eighth;...
FFour,Eighth; CFive,Eighth; EFour,Eighth; FFour,Eighth; CFive,Eighth; EFour,Eighth; FFour,Eighth;...
BFour,Eighth; BFour,Eighth; EFour,Eighth; FFour,Eighth; BFour,Eighth; EFour,Eighth; FFour,Eighth;...
CFive,Eighth; EFour,Eighth; FFour,Eighth; CFive,Eighth; EFour,Eighth; FFour,Eighth; CFive,Eighth;...
EFour,Eighth; FFour,Eighth; BFour,Eighth; EFour,Eighth; FFour,Eighth; BFour,Eighth; EFour,Eighth;...
FFour,Eighth; CFive,Eighth; EFour,Eighth; FFour,Eighth; CFive,Eighth; EFour,Eighth; FFour,Eighth;...
CFive,Eighth; EFour,Eighth; FFour,Eighth; BFour,Eighth; BFour,Eighth; EFour,Eighth; FFour,Eighth;...
BFour,Eighth; EFour,Eighth; FFour,Eighth; CFive,Eighth; EFour,Eighth; FFour,Eighth; GFour,Eighth;...
FFour,Eighth; Rest,Eighth; GFour,Eighth; FFour,Eighth; Rest,Eighth; GFour,Eighth; FFour,Eighth;...
GFour,Eighth; FFour,Eighth; Rest,Eighth; GFour,Eighth; FFour,Eighth; Rest,Eighth; GFour,Eighth;...
FFour,Eighth; FFour,Eighth; Rest,Quarter
];
AlarmSongSilhouette=[BThree,Eighth;FThree,Eighth;BThree,Eighth;DFour,DottedEighth;Rest,Sixteenth;...
AThree,Eighth;BThree,Eighth;AThree,Eighth;BThree,Eighth;DFour,DottedEighth;Rest,Sixteenth;DFive,DottedQuarter;...
AFour,DottedQuarter;DFive,Quarter;EFive,DottedQuarter;AFour,DottedQuarter;EFive,Quarter;FFive,DottedQuarter;...
GFive,DottedQuarter;FFive,Eighth;EFive,Eighth;DFive,DottedQuarter;GFive,DottedQuarter;FSix,Quarter;DSix,DottedQuarter;...
GSix,DottedQuarter;FSix,Quarter;ESix,DottedHalf;Rest,Quarter;GSix,DottedQuarter;FSix,DottedQuarter;...
DSix,Quarter;ESix,DottedQuarter;ESix,DottedQuarter;CSix,Quarter;FFour,Quarter;DFour,Quarter;EFour,Quarter;...
FFour,Half;GTwo,Quarter;GOne,Eighth;DTwo,Eighth;DFour,Quarter;FFour,Eighth;FFour,Eighth;...
EFour,Eighth;DFour,Eighth;EFour,Quarter;AFour,Eighth;AFour,DottedQuarter;EFour,Quarter;CFour,Quarter;...
EFour,Quarter;DFour,Quarter;Rest,Quarter;BFour,Quarter;AFour,Quarter;DFour,Quarter;Rest,Quarter;BFour,Quarter;...
AFour,Quarter;DFour,Quarter;Rest,Quarter;AFour,Quarter;AFour,Quarter;CFour,Quarter;AFour,Quarter;EFour,Quarter;...
DFour,Quarter;FFour,Quarter;DFour,Quarter;EFour,Eighth;EFour,Eighth;FFour,Half;DTwo,Quarter;GOne,Eighth;...
DTwo,Eighth;DFour,Eighth;DFour,Eighth;FFour,Quarter;EFour,Eighth;DFour,Eighth;EFour,Quarter;...
AFour,Eighth;AFour,DottedQuarter;EFour,Quarter;CFour,Quarter;EFour,Quarter;DFour,Quarter;Rest,Quarter;...
BFour,Quarter;AFour,Quarter;DFour,Quarter;Rest,Quarter;DFour,Quarter;DFour,Quarter;CFour,Quarter;...
DFour,Quarter;EFour,Quarter;DFour,Quarter;AThree,Eighth;FFour,Quarter;FFour,Eighth;];
AlarmSongBrightSide=[DFive,Eighth;FFive,Eighth;DSix,Eighth;FFive,Eighth;EFive,Eighth;ESix,Eighth;DSix,Eighth;...
DFour,Eighth;CFive,Eighth;FFive,Eighth;DSix,Eighth;FFive,Eighth;EFive,Eighth;ESix,Eighth;DSix,Eighth;...
DFour,Eighth;GFour,Eighth;FFive,Eighth;DSix,Eighth;FFive,Eighth;EFive,Eighth;ESix,Eighth;DSix,Eighth;...
DFour,Eighth;GFour,Eighth;FFive,Eighth;DSix,Eighth;FFive,Eighth;EFive,Eighth;ESix,Eighth;DSix,Eighth;...
DFour,Eighth;DFive,Eighth;FFive,Eighth;DSix,Eighth;FFive,Eighth;EFive,Eighth;ESix,Eighth;DSix,Eighth;...
DFour,Eighth;CFive,Eighth;FFive,Eighth;DSix,Eighth;FFive,Eighth;EFive,Eighth;ESix,Eighth;DSix,Eighth;...
DFour,Eighth;GFour,Eighth;FFive,Eighth;DSix,Eighth;FFive,Eighth;EFive,Eighth;ESix,Eighth;DSix,Eighth;...
DFour,Eighth;GFour,Eighth;FFive,Eighth;DSix,Eighth;FFive,Eighth;EFive,Eighth;ESix,Eighth;DSix,Eighth;...
DFour,Eighth;DFive,Eighth;FFive,Eighth;DSix,Eighth;FFive,Eighth;EFive,Eighth;ESix,Eighth;DSix,Eighth;...
DFour,Eighth;CFive,Eighth;FFive,Eighth;DSix,Eighth;FFive,Eighth;EFive,Eighth;ESix,Eighth;DSix,Eighth;...
DFour,Eighth;GFour,Eighth;FFive,Eighth;DSix,Eighth;FFive,Eighth;EFive,Eighth;ESix,Eighth;DSix,Eighth;...
DFour,Eighth;GFour,Eighth;FFive,Eighth;DSix,Eighth;FFive,Eighth;EFive,Eighth;ESix,Eighth;DSix,Eighth;...
DFour,Eighth;BOne,Eighth;GFour,Eighth;BOne,Eighth;GFour,Eighth;BOne,Eighth;GFour,Eighth;BOne,Eighth;GFour,Eighth;...
BOne,Eighth;GFour,Eighth;AOne,Eighth;FFour,Eighth;AOne,Eighth;FFour,Eighth;AOne,Eighth;FFour,Eighth;AOne,Eighth;...
FFour,Eighth;AOne,Eighth;FFour,Eighth;AOne,Eighth;FFour,Eighth;AOne,Eighth;FFour,Eighth;AOne,Eighth;FFour,Eighth;...
GOne,Eighth;GTwo,Eighth;GOne,Eighth;GTwo,Eighth;GOne,Eighth;GTwo,Eighth;GOne,Eighth;GTwo,Eighth;GOne,Eighth;GTwo,Eighth;...
GOne,Eighth;GTwo,Eighth;GOne,Eighth;GTwo,Eighth;GOne,Eighth;GTwo,Eighth;GOne,Eighth;GTwo,Eighth;GOne,Eighth;GTwo,Eighth;...
GOne,Eighth;GTwo,Eighth;GOne,Eighth;GTwo,Eighth;GOne,Eighth;GTwo,Eighth;GOne,Eighth;GTwo,Eighth;GOne,Eighth;GTwo,Eighth;...
GOne,Eighth;GTwo,Eighth;];
AlarmSongPinkPony=[BThree,Whole;BThree,Sixteenth;EFive,Sixteenth;GFive,Sixteenth;CSix,Sixteenth;GFive,Sixteenth;...
GFive,Eighth;EFive,Sixteenth;GFive,Sixteenth;CSix,Sixteenth;GFive,Sixteenth;Rest,Eighth;EFive,Sixteenth;...
GFive,Sixteenth;CSix,Sixteenth;GFive,Sixteenth;EFive,Sixteenth;EFive,Eighth;EFour,ThirtySecond;GFour,ThirtySecond;...
CFive,Sixteenth;BFour,Sixteenth;GFour,Sixteenth;GFour,Eighth;EFour,Quarter;EFour,Quarter;EFour,Eighth;CThree,Eighth;...
GTwo,Eighth;GTwo,Quarter;CFour,Eighth;CFour,Half;CFour,Whole;FFour,DottedEighth;FFour,Sixteenth;FFour,Quarter;...
Rest,DottedQuarter;FFour,Eighth;EFour,Eighth;FFour,Eighth;EFour,Eighth;FFour,Eighth;EFour,Quarter;Rest,Eighth;...
GThree,Sixteenth;GThree,Sixteenth;CFour,Eighth;CFour,Eighth;CFour,DottedEighth;CFour,Sixteenth;DFour,Eighth;...
CFour,Eighth;CFour,Sixteenth;AThree,Sixteenth;AThree,Eighth;BThree,Eighth;AThree,Sixteenth;BThree,Eighth;AThree,Sixteenth;...
AThree,Quarter;Rest,Quarter;FFour,DottedEighth;FFour,Sixteenth;FFour,Quarter;Rest,DottedQuarter;FFour,Eighth;...
EFour,Eighth;FFour,Eighth;EFour,Eighth;FFour,Eighth;EFour,Quarter;Rest,DottedEighth;BThree,Sixteenth;CFour,Eighth;CFour,Eighth;CFour,DottedEighth;CFour,Sixteenth;DFour,Eighth;...
CFour,Eighth;CFour,Sixteenth;AThree,Sixteenth;AThree,Eighth;BThree,Eighth;AThree,Sixteenth;BThree,Eighth;AThree,Sixteenth;...
AThree,Quarter;Rest,Quarter;Rest,Eighth;AFour,Eighth;AFour,Eighth;AFour,Eighth;AFour,Eighth;AFour,Eighth;CFive,Quarter;...
Rest,Eighth;BFour,Eighth;BFour,Eighth;BFour,Eighth;BFour,Eighth;BFour,Eighth;Rest,Eighth;CFive,Eighth;CFive,Eighth;...
CFive,Eighth;CFive,Eighth;CFive,Eighth;EFive,Quarter;Rest,Eighth;DFive,Eighth;DFive,Eighth;DFive,Eighth;DFive,Eighth;...
DFive,Eighth;FFive,Quarter;Rest,Eighth;Rest,Eighth;AFour,Eighth;AFour,Eighth;AFour,Eighth;AFour,Eighth;AFour,Eighth;CFive,Quarter;...
Rest,Eighth;BFour,Eighth;BFour,Eighth;BFour,Eighth;BFour,Eighth;BFour,Eighth;Rest,Eighth;CFive,Eighth;CFive,Eighth;...
CFive,Eighth;CFive,Eighth;CFive,Eighth;EFive,Quarter;Rest,Eighth;DFive,Eighth;DFive,Eighth;DFive,Eighth;DFive,Eighth;...
DFive,Eighth;FFive,Quarter;BFive,Eighth;CSix,Quarter;CSix,Eighth;CSix,Eighth;DSix,Eighth;AFive,Eighth;CSix,Eighth;CSix,Eighth;...
Rest,Quarter;GFive,Sixteenth;GFive,Sixteenth;GFive,Eighth;GFive,Eighth;GFive,Eighth;GFive,Eighth;FFive,Eighth;Rest,Quarter;...
EFive,Sixteenth;EFive,Sixteenth;EFive,Eighth;FFive,Eighth;CFive,Eighth;CFive,Eighth;DFive,Eighth;CFive,Quarter;...
CFive,Quarter;CFive,Quarter;BFive,Eighth;CSix,Half;CSix,Eighth;DSix,Eighth;AFive,Eighth;CSix,Eighth;];
AlarmSongPiano = [Rest,Half; FFour,Quarter; GFour,Half; GFour,Quarter; GFour,Half; FFour,Eighth;...
    EFour,Eighth; FFour,Eighth; EFour,Eighth; CFour,Quarter; Rest,Quarter; Rest,Quarter; Rest,Quarter;...
    CFour,Quarter; CFour,Quarter; CFour,Quarter; CFour,Quarter; CFour,Half; EFour,Half; EFour,Quarter;...
    EFour,DottedHalf; Rest,Quarter; Rest,Quarter; EFour,Eighth; FFour,Eighth; GFour,Half; GFour,Quarter;...
    GFour,Half; FFour,Eighth; EFour,Eighth; FFour,Eighth; EFour,Eighth; CFour,Half; Rest,Quarter;...
    Rest,Quarter; CFour,Quarter; Rest,Quarter; Rest,Quarter; EFour,Quarter; FFour,Quarter; EFour,Quarter;...
    CFour,Quarter; CFour,DottedHalf; Rest,DottedHalf; Rest,Quarter; FFour,Quarter; GFour,Quarter;...
    GFour,Half; GFour,Quarter; GFour,Half; FFour,Eighth; EFour,Eighth; FFour,Eighth; EFour,Eighth;...
    CFour,Half; Rest,Quarter; Rest,Quarter; CFour,Quarter; CFour,Quarter; CFour,Quarter; CFour,Quarter;...
    CFour,Half; DFour,Quarter; DFour,DottedHalf; Rest,Quarter; Rest,Quarter; EFour,Eighth; FFour,Eighth;...
    GFour,Quarter; GFour,Quarter; GFour,Quarter; GFour,Half; FFour,Eighth; EFour,Eighth; FFour,Quarter;...
    EFour,Quarter; EFour,Quarter; EFour,Half; CFour,Quarter; CFour,Quarter; CFour,Quarter; EFour,Quarter;...
    FFour,Quarter; EFour,Quarter; CFour,Quarter; CFour,DottedHalf; AFour,DottedHalf; AFour,Half; BFour,Eighth;...
    CFive,Eighth; BFour,Quarter; AFour,Quarter; Rest,Quarter; Rest,DottedHalf; Rest,Quarter; AFour,Quarter;...
    AFour,Quarter; AFour,Half; BFour,Eighth; CFive,Eighth; BFour,DottedHalf; Rest,Quarter; Rest,Quarter;...
    AFour,Quarter; GFour,DottedHalf; FThree,DottedHalf; EThree,DottedHalf; DThree,DottedHalf; GFour,Quarter;...
    GFour,Quarter; GFour,Quarter; GFour,Half; FFour,Eighth; EFour,Eighth; FFour,Eighth; EFour,Eighth; CFour,Half;...
    Rest,DottedHalf; CFour,Quarter; CFour,Quarter; CFour,Quarter; CFour,Half; EFour,Quarter; DFour,DottedHalf;...
    Rest,Quarter; EFour,Quarter; FFour,Quarter; GFour,Half; GFour,Quarter; GFour,Half; FFour,Eighth; EFour,Eighth;...
    FFour,Eighth; EFour,Eighth; CFour,Half; Rest,Quarter; Rest,Quarter; CFour,Quarter; Rest,Quarter; Rest,Quarter;...
    EFour,Quarter; FFour,Quarter; EFour,Quarter; CFour,Quarter; CFour,DottedHalf];
if SongNum == 1
    while 1==1
        while 1==1
            for idx = 1 : length(AlarmSongMega)
                playTone(comThree,'D3',AlarmSongMega(idx,1),AlarmSongMega(idx,2))
                pause(AlarmSongMega(idx,2))
            end
        end
    end
elseif SongNum == 2 
    while 1==1
        while 1==1
            for idx = 1 : length(AlarmSongCommrad)
                playTone(comThree,'D3',AlarmSongCommrad(idx,1),AlarmSongCommrad(idx,2))
                pause(AlarmSongCommrad(idx,2))
            end
        end
    end
elseif SongNum == 3
    while 1==1
        while 1==1
            for idx = 1 : length(AlarmSongCallMe)
                playTone(comThree,'D3',AlarmSongCallMe(idx,1),AlarmSongCallMe(idx,2))
                pause(AlarmSongCallMe(idx,2))
            end
        end
    end
elseif SongNum ==4
    while 1==1
        while 1==1
            for idx = 1 : length(AlarmSongPuppet)
                playTone(comThree,'D3',AlarmSongPuppet(idx,1),AlarmSongPuppet(idx,2))
                pause(AlarmSongPuppet(idx,2))
            end
        end
    end
elseif SongNum ==5
    while 1==1
        while 1==1
            for idx = 1 : length(AlarmSongSilhouette)
                playTone(comThree,'D3',AlarmSongSilhouette(idx,1),AlarmSongSilhouette(idx,2))
                pause(AlarmSongSilhouette(idx,2))
            end
        end
    end
elseif SongNum == 6 
    while 1==1
        while 1==1
            for idx = 1 : length(AlarmSongBrightSide)
                playTone(comThree,'D3',AlarmSongBrightSide(idx,1),AlarmSongBrightSide(idx,2))
                pause(AlarmSongBrightSide(idx,2))
            end
        end
    end
elseif SongNum==7
    while 1==1
        for idx = 1 : length(AlarmSongPinkPony)
            playTone(comThree,'D3',AlarmSongPinkPony(idx,1),AlarmSongPinkPony(idx,2))
            pause(AlarmSongPinkPony(idx,2))
        end
    end
elseif SongNum==8
    while 1==1
        for idx = 1 : length(AlarmSongPiano)
            playTone(comThree,'D3',AlarmSongPiano(idx,1),AlarmSongPiano(idx,2))
            pause(AlarmSongPiano(idx,2))
        end
    end
end
